services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            # MYSQL_USER: ${DB_USERNAME}
            # MYSQL_PASSWORD: ${DB_PASSWORD}
            TZ: Europe/Berlin
        ports:
            - "${DB_PORT}:3306"
